minor fix

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -66,7 +66,15 @@ jobs:
       - name: Terraform Init
         id: init
         run: terraform init
-        
+
+      - name: Import Resource
+        id: import_rg
+        run: |
+          set +e  # Disable exit on error
+          terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/sockshop_capstone-rg
+          echo "Import step completed."
+          set -e  # Re-enable exit on error    
+    
       - name: Terraform Validate
         id: validate
         run: terraform validate
